### ISSUE TITLE
LinkedList错误

### ISSUE THREAD

**Issue by BUGLAN** [PegasusWang/python_data_structures_and_algorithms#11]
当链表执行完clear方法时 assert list(ll)==[] 错误
```
AttributeError: 'NoneType' object has no attribute 'value'
```
应当在iter_node中加入判断
```python
if self.tailnode is None:                                              
    return None
```
在clear()中加入
```
self.tailnode = None
```

**Comment by PegasusWang** [comment]
hi，感谢提出。这里确实有问题。已经修改， MR：https://github.com/PegasusWang/python_data_structures_and_algorithms/commit/07ad56e79e0dbdeba5544dec40a1241417abaec1
