### ISSUE TITLE
[建议]教材介绍中追加勘误页的链接

### ISSUE THREAD

**Issue by lhsfcboy** [PegasusWang/python_data_structures_and_algorithms#13]
Data Structures and Algorthms Using Python (数据结构与算法 Python实现版) 书中的小错误太多太多了.

最好能对照本书的官方勘误来阅读:

<http://bcs.wiley.com/he-bcs/Books?action=resource&bcsId=9003&itemId=0470618299&resourceId=35653>

**Comment by PegasusWang** [comment]
是的，这本英文书当时看的时候也是非常多的错误，代码很多是难以直接运行的。好在 github 上的电子书可以及时修复。

**Comment by PegasusWang** [comment]
已经增加到 readme
