### ISSUE TITLE
LinkedList中appendleft方法

### ISSUE THREAD

**Issue by HanZhengDe** [PegasusWang/python_data_structures_and_algorithms#14]
appendleft方法应该加入以下代码，否则新建链表先用appendleft再用append，会导致appendleft加入的节点丢失
`if self.tailnode is None:
     self.tailnode = node`

**Comment by PegasusWang** [comment]
hi， 感谢指出。已经修复并增加了单测。
https://github.com/PegasusWang/python_data_structures_and_algorithms/commit/d23332b531b6a8652f206115cd48ffbf667623fe
