### ISSUE TITLE
关于Hash的问题

### ISSUE THREAD

**Issue by yuyijie1995** [PegasusWang/python_data_structures_and_algorithms#18]
class Slot(object):
    """定义一个 hash 表 数组的槽
    注意，一个槽有三种状态，看你能否想明白
    1.从未使用 HashMap.UNUSED。此槽没有被使用和冲突过，查找时只要找到 UNUSED 就不用再继续探查了
    2.使用过但是 remove 了，此时是 HashMap.EMPTY，该探查点后边的元素扔可能是有key
    3.槽正在使用 Slot 节点
    """
    def __init__(self, key, value):
        self.key, self.value = key, value

这里的“  2.使用过但是 remove 了，此时是 HashMap.EMPTY，该探查点后边的元素扔可能是有key”remove之后曹不应该为空了么 仍有可能是有key是什么意思

**Comment by PegasusWang** [comment]
因为使用的是二次探查的方式，假如有两个元素 A，B 冲突了，首先A hash 得到是 slot 下标5，A 放到了第5个槽，之后插入 B 因为冲突了，所以继续根据二次探查方式放到了 slot8。
然后删除 A，槽 5 被置为 EMPTY。然后我去查找 B，第一次 hash 得到的是 槽5，但是这个时候我还是需要二次 hash 才能找到 B，所以需要再次计算才找到 B。但是如果槽是 UNUSED 我就不用继续找了，我认为 B 就是不存在的元素。这个就是 UNUSED 和 EMPTY 的区别。
