### ISSUE TITLE
关于您python-web-guide仓库的一个问题

### ISSUE THREAD

**Issue by Shimada666** [PegasusWang/python_data_structures_and_algorithms#25]
那里没有issue区,故在此提一下issue
clone了您最新代码, make serve报错
Warning, treated as error:
/root/python-web-guide-master/codingstyle/codingstyle.rst:182: ERROR: Unknown target name: "\u300athe elements of programming style\u300bhttps://en.wikipedia.org/wiki/the_elements_of_programming_style>".

centos7.6 ubuntu18.04 win10上均是此问题, 127.0.0.1:8000显示404

**Comment by PegasusWang** [comment]
拉一下最新的代码，然后 pip install -r requirements.txt 。我本地 make serve 是没有问题的。
