### ISSUE TITLE
冒泡算法

### ISSUE THREAD

**Issue by amusi** [PegasusWang/python_data_structures_and_algorithms#4]
冒泡算法介绍时，"它的思想如下。对一个数组进行 n 轮迭代，每次比较相邻两个元素"，这里应该是 n-1吧，因为程序也是这样写的，所以为了统一，建议修改为n-1。

link：https://github.com/PegasusWang/python_data_structures_and_algorithms/blob/master/docs/12_%E5%9F%BA%E6%9C%AC%E6%8E%92%E5%BA%8F%E7%AE%97%E6%B3%95/basic_sort.md

**Comment by PegasusWang** [comment]
这里其实当时为了强调是 O(n)，确实不太严谨。已经修改
