### ISSUE TITLE
关于bst删除节点时的两个疑问

### ISSUE THREAD

**Issue by hjlarry** [PegasusWang/python_data_structures_and_algorithms#9]
请教两个问题，谢谢

一、 “删除只有一个孩子的节点时，只要把它的父亲指向它的孩子”，这里貌似有问题，例如：
root的key为60，左孩子为10，右孩子为70，然后70的左孩子为30
若删除70这个节点，则按上述规则30将会成为60的右孩子，不符合bst特性

二、 删除两个孩子的节点时，代码是这么写的：
successor_node = self._bst_min_node(subtree.right)
subtree.key, subtree.value = successor_node.key, successor_node.value
subtree.right = self._bst_remove(subtree.right, successor_node.key)

既然是互换了两个节点，为什么要最后一行给互换后节点的右孩子再去赋值？是否直接self._bst_remove(subtree.right, successor_node.key)就可以了？

**Comment by PegasusWang** [comment]
1. 第一个问题，插入的时候 30 是不会成为 70 的左孩子的，按照 bst 的插入特性，30 只会插入到 root 的左子树，因为比 root 的 60 要小，所以这个前提不会成立。

2. 删除两个孩子的内部节点有三个步骤：
- 找到待删除节点 N(12) 的后继节点 S(23)
- 复制节点 S 到节点 N
- 从 N 的右子树中删除节点 S
这里赋值的意思是表明把当前子树的右子树更新为删除后继节点后的子树，假如右子树此时为 None 了就需要更新。

最后，交换的地方确实有个手误，感谢及时发现，已经合并。

**Comment by hjlarry** [comment]
感谢大佬 两个问题都已想明白了

**Comment by PegasusWang** [comment]
好，如果解答了你的疑问这个 issue 我就 close 了
